In [1]:
import torch
import pandas as pd
from torch import nn
from torch.utils.data import DataLoader, Dataset

In [8]:
class Test(nn.Module):
    def __init__(self):
        super(Test,self).__init__()
        self.register_module("fc",nn.Linear(10,100))
        self.fc2 = nn.Linear(100,1000)

    def forward(self,x):
        return x

In [15]:
test = Test()
for i in test.named_children():
    print(i)

('fc', Linear(in_features=10, out_features=100, bias=True))
('fc2', Linear(in_features=100, out_features=1000, bias=True))


In [19]:
a = torch.ones(5,requires_grad=False)
b = torch.randn(5)
c = a + b
d = torch.ones(1,5)
f = d * c
print(c)
print(a)
print(b)
print(f)

tensor([ 1.3686, -0.9640,  0.4653,  0.3602,  1.7615])
tensor([1., 1., 1., 1., 1.])
tensor([ 0.3686, -1.9640, -0.5347, -0.6398,  0.7615])
tensor([[ 1.3686, -0.9640,  0.4653,  0.3602,  1.7615]])


In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [8]:
x = torch.tensor([1.0,1,2,3])
y = torch.tensor([3,1,2,3])
z = x + y
z

tensor([4., 2., 4., 6.])

In [9]:
z.sum()

tensor(16.)

In [10]:
Y = torch.arange(24).reshape((3,8))
Y

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
Y[-1]

tensor([16, 17, 18, 19, 20, 21, 22, 23])

In [14]:
Y[0:2]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [16]:
Y[1,1] = 10
Y

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8, 10, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])

In [17]:
X = torch.arange(24).reshape((3,8))
X

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
X += Y
X

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14],
        [16, 19, 20, 22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40, 42, 44, 46]])

In [19]:
X[:] = X + Y

In [20]:
X

tensor([[ 0,  3,  6,  9, 12, 15, 18, 21],
        [24, 29, 30, 33, 36, 39, 42, 45],
        [48, 51, 54, 57, 60, 63, 66, 69]])

In [22]:
data = pd.read_csv("./lab1/data/covid.train.csv")
print(data)

        id  AL  AK  AZ  AR  CA  CO  CT  FL  GA  ...  work_outside_home.4  \
0        0   0   0   0   0   0   0   0   1   0  ...            31.113209   
1        1   0   0   0   0   0   1   0   0   0  ...            33.920257   
2        2   0   0   0   0   0   0   0   0   0  ...            31.604604   
3        3   0   0   0   0   0   0   0   0   0  ...            35.115738   
4        4   0   0   0   0   0   0   0   0   0  ...            35.129714   
...    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...                  ...   
2694  2695   0   0   0   0   0   0   0   0   0  ...            39.209278   
2695  2696   0   0   0   0   0   0   0   0   0  ...            28.984491   
2696  2697   0   0   0   1   0   0   0   0   0  ...            34.346100   
2697  2698   0   0   0   0   0   0   0   0   0  ...            30.451071   
2698  2699   0   0   0   0   0   0   0   0   0  ...            33.803854   

         shop.4  restaurant.4  spent_time.4  large_event.4  public_transit.4  \
0     6

In [24]:
data

id  AL  AK  AZ  AR  CA  CO  CT  FL  GA  ...  work_outside_home.4  \
0        0   0   0   0   0   0   0   0   1   0  ...            31.113209   
1        1   0   0   0   0   0   1   0   0   0  ...            33.920257   
2        2   0   0   0   0   0   0   0   0   0  ...            31.604604   
3        3   0   0   0   0   0   0   0   0   0  ...            35.115738   
4        4   0   0   0   0   0   0   0   0   0  ...            35.129714   
...    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...                  ...   
2694  2695   0   0   0   0   0   0   0   0   0  ...            39.209278   
2695  2696   0   0   0   0   0   0   0   0   0  ...            28.984491   
2696  2697   0   0   0   1   0   0   0   0   0  ...            34.346100   
2697  2698   0   0   0   0   0   0   0   0   0  ...            30.451071   
2698  2699   0   0   0   0   0   0   0   0   0  ...            33.803854   

         shop.4  restaurant.4  spent_time.4  large_event.4  public_transit.4  \
0     67.394551     36.674291     40.743132      17.842221          4.093712   
1     64.398380     34.612238     44.035688      17.808103          4.924935   
2     62.101064     26.521875     36.746453      13.903667          7.313833   
3     67.935520     38.022492     48.434809      27.134876          3.101904   
4     69.934592     38.242368     49.095933      22.683709          4.594620   
...         ...           ...           ...            ...               ...   
2694  65.815096     37.046827     46.777637      21.952499          2.724187   
2695  66.126427     31.299807     40.399527      16.783327         14.058799   
2696  63.456270     30.829009     41.828908      20.597714          2.391852   
2697  67.477177     33.975333     45.837535      18.437260          3.088666   
2698  66.374538     38.493176     41.290529      19.225268          5.326241   

      anxious.4  depressed.4  worried_finances.4  tested_positive.4  
0     10.440071     8.627117           37.329512           7.456154  
1     10.172662     9.954333           32.508881           8.010957  
2     10.388712     7.956139           36.745588           2.906977  
3     10.498683     8.231522           38.680162          12.575816  
4      9.878927     9.469290           28.344123          21.428589  
...         ...          ...                 ...                ...  
2694  14.658436    11.099308           33.154910          13.437482  
2695  13.129031    10.492896           36.670282           5.040143  
2696  16.940896    12.888275           42.452451          13.618256  
2697  12.621144    10.096939           29.668802           9.512585  
2698  13.157865     9.618114           37.744195          11.069423  

[2699 rows x 118 columns]

In [25]:
data.iloc[:,1]

0       0
1       0
2       0
3       0
4       0
       ..
2694    0
2695    0
2696    0
2697    0
2698    0
Name: AL, Length: 2699, dtype: int64

In [26]:
data.iloc[:,0:2]

id  AL
0        0   0
1        1   0
2        2   0
3        3   0
4        4   0
...    ...  ..
2694  2695   0
2695  2696   0
2696  2697   0
2697  2698   0
2698  2699   0

[2699 rows x 2 columns]

In [27]:
data.iloc[1:2,2]

1    0
Name: AK, dtype: int64

In [29]:
input = data.iloc[:,2:3]

In [31]:
type(input.values)

numpy.ndarray

In [37]:
x = torch.arange(20,dtype=float).reshape((4,5))
x.requires_grad_(True)
y = (x * 2).sum()
y

tensor(380., dtype=torch.float64, grad_fn=<SumBackward0>)

In [38]:
y.backward()

In [39]:
x.grad

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)